# .github/workflows/dispatch_with_branch.yml
name: Manual Branch-Based Runner

on:
  push:
    branches:
      - new   # Trigger automatically when 'new' branch is pushed
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to run against (e.g., main, feature-x)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run logic with specified branch
        env:
          SELECTED_REF: ${{ inputs.ref }}
        run: |
          echo "Running workflow for branch/tag: $SELECTED_REF"
          python3 testing.py 
