name: Docker Image CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # <--- Global environment variables for all steps
      DOCKER_IMAGE: "mynginx"
      DOCKER_TAG: "v1.03"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: python3 build.py

    - name: List Docker Images
      run: docker images

    - name: Run Docker Container
      run: docker run -d --name tom -p 80:80 $DOCKER_IMAGE:$DOCKER_TAG

    - name: Test Website with curl
      run: docker exec tom curl -s http://localhost:80
