name: Docker Image CI

on:
  workflow_dispatch
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out 
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: python3 build.py 
      env:
        DOCKER_IMAGE : "myNginx"
        DOCKER_TAG : v1.03"
